# Generated by Django 5.0.14 on 2026-04-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="الاسم")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="البريد الإلكتروني"),
                ),
                ("message", models.TextField(verbose_name="الرسالة")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإرسال"
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="تم القراءة"),
                ),
            ],
            options={
                "verbose_name": "رسالة تواصل",
                "verbose_name_plural": "رسائل التواصل",
                "ordering": ["-created_at"],
            },
        ),
    ]
