# Generated by Django 5.0.14 on 2026-04-24 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم المنطقة")),
                (
                    "slug",
                    models.SlugField(
                        max_length=100, unique=True, verbose_name="الرابط"
                    ),
                ),
                ("tagline", models.CharField(max_length=200, verbose_name="الشعار")),
                ("brief", models.TextField(verbose_name="نبذة مختصرة")),
                (
                    "top_attraction",
                    models.CharField(max_length=200, verbose_name="أبرز معلم"),
                ),
                ("history", models.TextField(verbose_name="التاريخ")),
                (
                    "video_url",
                    models.URLField(blank=True, null=True, verbose_name="رابط الفيديو"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "منطقة",
                "verbose_name_plural": "المناطق",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Craft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="اسم الحرفة")),
                (
                    "slug",
                    models.SlugField(
                        max_length=200, unique=True, verbose_name="الرابط"
                    ),
                ),
                ("description", models.TextField(verbose_name="الوصف")),
                ("image", models.CharField(max_length=300, verbose_name="مسار الصورة")),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="حرفة مميزة"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crafts",
                        to="crafts.region",
                        verbose_name="المنطقة",
                    ),
                ),
            ],
            options={
                "verbose_name": "حرفة",
                "verbose_name_plural": "الحرف اليدوية",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RegionEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="اسم الفعالية")),
                ("order", models.IntegerField(default=0, verbose_name="الترتيب")),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="crafts.region",
                        verbose_name="المنطقة",
                    ),
                ),
            ],
            options={
                "verbose_name": "فعالية",
                "verbose_name_plural": "الفعاليات",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="RegionImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.CharField(max_length=300, verbose_name="مسار الصورة")),
                ("order", models.IntegerField(default=0, verbose_name="الترتيب")),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="crafts.region",
                        verbose_name="المنطقة",
                    ),
                ),
            ],
            options={
                "verbose_name": "صورة المنطقة",
                "verbose_name_plural": "صور المناطق",
                "ordering": ["order"],
            },
        ),
    ]
