# Generated by Django 6.0.4 on 2026-04-25 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crafts", "0002_comment_favorite_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="craft",
            name="description_ar",
            field=models.TextField(null=True, verbose_name="الوصف"),
        ),
        migrations.AddField(
            model_name="craft",
            name="description_en",
            field=models.TextField(null=True, verbose_name="الوصف"),
        ),
        migrations.AddField(
            model_name="craft",
            name="name_ar",
            field=models.CharField(
                max_length=200, null=True, verbose_name="اسم الحرفة"
            ),
        ),
        migrations.AddField(
            model_name="craft",
            name="name_en",
            field=models.CharField(
                max_length=200, null=True, verbose_name="اسم الحرفة"
            ),
        ),
        migrations.AddField(
            model_name="region",
            name="brief_ar",
            field=models.TextField(null=True, verbose_name="نبذة مختصرة"),
        ),
        migrations.AddField(
            model_name="region",
            name="brief_en",
            field=models.TextField(null=True, verbose_name="نبذة مختصرة"),
        ),
        migrations.AddField(
            model_name="region",
            name="history_ar",
            field=models.TextField(null=True, verbose_name="التاريخ"),
        ),
        migrations.AddField(
            model_name="region",
            name="history_en",
            field=models.TextField(null=True, verbose_name="التاريخ"),
        ),
        migrations.AddField(
            model_name="region",
            name="name_ar",
            field=models.CharField(
                max_length=100, null=True, verbose_name="اسم المنطقة"
            ),
        ),
        migrations.AddField(
            model_name="region",
            name="name_en",
            field=models.CharField(
                max_length=100, null=True, verbose_name="اسم المنطقة"
            ),
        ),
        migrations.AddField(
            model_name="region",
            name="tagline_ar",
            field=models.CharField(max_length=200, null=True, verbose_name="الشعار"),
        ),
        migrations.AddField(
            model_name="region",
            name="tagline_en",
            field=models.CharField(max_length=200, null=True, verbose_name="الشعار"),
        ),
        migrations.AddField(
            model_name="region",
            name="top_attraction_ar",
            field=models.CharField(max_length=200, null=True, verbose_name="أبرز معلم"),
        ),
        migrations.AddField(
            model_name="region",
            name="top_attraction_en",
            field=models.CharField(max_length=200, null=True, verbose_name="أبرز معلم"),
        ),
        migrations.AddField(
            model_name="regionevent",
            name="name_ar",
            field=models.CharField(
                max_length=200, null=True, verbose_name="اسم الفعالية"
            ),
        ),
        migrations.AddField(
            model_name="regionevent",
            name="name_en",
            field=models.CharField(
                max_length=200, null=True, verbose_name="اسم الفعالية"
            ),
        ),
    ]
